### ISSUE TITLE
Renommer le dépôt Git

### ISSUE THREAD

**Issue by eduardokraus** [Kaloomc/moodle-local_resend_password_profile#2]
Le nom actuel du dépôt Git ne suit pas la convention standard. Pour garantir la cohérence et faciliter l'identification, je propose que le nom du dépôt soit modifié en "moodle-local_resend_password_profile".

### Motivation :

- Améliore la clarté sur la fonctionnalité du dépôt.
- Facilite la recherche et la gestion au sein de l'écosystème Moodle.

### Action demandée :

- Changer le nom du dépôt en "moodle-local_resend_password_profile".

**Comment by Kaloomc** [comment]
C'est fait ! merci du conseil !
