### ISSUE TITLE
ci.yml to 100%

### ISSUE THREAD

**Issue by eduardokraus** [Kaloomc/moodle-local_resend_password_profile#3]
https://github.com/Kaloomc/moodle-local_resend_password_profile/actions/workflows/ci.yml

## Tous les commentaires nécessitent un point final (".").
https://github.com/Kaloomc/moodle-local_resend_password_profile/blob/master/lib.php#L40
https://github.com/Kaloomc/moodle-local_resend_password_profile/blob/master/resend_email.php#L29

## N'utilisez pas "array()", utilisez plutôt "[]"
https://github.com/Kaloomc/moodle-local_resend_password_profile/blob/master/resend_email.php#L40

## n'utilisez pas "print_error()"
Since 2021, it has been [agreed to deprecate print_error()](https://tracker.moodle.org/browse/MDL-69936) and, instead, to throw moodle_exception() is the correct way to proceed.

https://github.com/Kaloomc/moodle-local_resend_password_profile/blob/master/resend_email.php#L44

## Variable "$message_template" must not contain underscores.
Renommer $message_template en $messagetemplate

https://github.com/Kaloomc/moodle-local_resend_password_profile/blob/master/resend_email.php#L59

## Enfin, Moodle exige que les chaînes soient classées par ordre alphabétique.

https://github.com/Kaloomc/moodle-local_resend_password_profile/blob/master/lang/fr/local_resend_password_profile.php#L45

**Comment by Kaloomc** [comment]
everything done !
